[package]
name = "hello_worker"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
webworker = { path = "../.." }
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"

